export enum ActionType {
 REMOVE_POST = 'REMOVE_POST',
 LOAD_POSTS = 'LOAD_POSTS',
 LOAD_POSTS_ERROR = 'LOAD_POSTS_ERROR',
 LOAD_USERS = 'LOAD_USERS',
 LOAD_USERS_ERROR = 'LOAD_USERS_ERROR',
 LOAD_COMMENTS = 'LOAD_COMMENTS',
 LOAD_COMMENTS_ERROR = 'LOAD_COMMENTS_ERROR',
 LOGIN = 'LOGIN',
 LOGOUT = 'LOGOUT',
}